### ISSUE TITLE
The contents of this lab are only shown in the next section on canvas.

### ISSUE THREAD

**Issue by cayke-fda** [learn-co-curriculum/dsc-data-viz-lab#3]
## Link to Canvas

https://learning.flatironschool.com/courses/8017/assignments/277410?module_item_id=673520

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ X] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

### Concern

This lab starts working with a more object oriented way to plot figures using matplotlib (using "fig, ax = plt.subplots(figsize=(8, 6))") that is only shown in the next section on canvas. This might be a bit confusing to people seeing this for the first time.

## (Optional) Proposed Solution

Introducing this notion earlier on the class file.

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [X ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you for flagging this. We'll take a look.

**Comment by bpurdy-ds** [comment]
Thank you again. I passed it along to the team member that is updating/revising the Prep content and so we'll aim to implement this in the next release of the curriculum.
